FROM golang:1.17 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app

FROM scratch

WORKDIR /app

COPY --from=builder /app/app .
COPY --from=builder /app/templates ./templates

EXPOSE 8080

CMD ["./app", "serve"]

