FROM golang:1.17 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o app

FROM gcr.io/distroless/static-debian13

WORKDIR /app

COPY --from=builder /app/app .
COPY --from=builder /app/templates ./templates

EXPOSE 8080

CMD ["./app", "serve"]

