---
name: Deploy
on:  # yamllint disable-line rule:truthy
  push: null
    #tags:
      #- v*
jobs:
  deploy:
    runs-on:
      - self-hosted
      - deployment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519

          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -H ${{ secrets.TARGET_HOST }} >> ~/.ssh/known_hosts
      - name: Copy files to target
        run: >
          scp ./lab3/scripts/cd/deploy.sh \
            ${{ secrets.TARGET_USER }}@ \
            ${{ secrets.TARGET_HOST }}:/opt/mywebapp/deploy.sh

          scp ./lab3/docker-compose.yml \
            ${{ secrets.TARGET_USER }}@ \
            ${{ secrets.TARGET_HOST }}:/opt/mywebapp/docker-compose.yml

          scp ./lab3/migrate.sql \
            ${{ secrets.TARGET_USER }}@ \
            ${{ secrets.TARGET_HOST }}:/opt/mywebapp/migrate.sql

          scp ./lab3/nginx.conf \
            ${{ secrets.TARGET_USER }}@ \
            ${{ secrets.TARGET_HOST }}:/opt/mywebapp/nginx.conf
      - name: Run deployment
        run: |
          ssh \
            ${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }} \
            'chmod +x /opt/mywebapp/deploy.sh && bash /opt/mywebapp/deploy.sh'
