---
name: Test
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('lab3/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests and coverage
        run: mvn verify
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: lab3/target/site/jacoco
